language: c
os:
  - linux
  - osx

sudo: false

addons:
  apt:
    packages:
    - fish

before_install:
  - curl -L git.io/wa | sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/88afd36810236434b92e
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
