language: c
os:
  - linux
#  - osx # currently not supported
sudo: false
addons:
  apt:
    packages:
    - tree
    - fish
before_script: pwd; tree -h
script: /bin/sh bootstrap.sh
after_script:
  - cd ~/.config/fish; tree -h; find . -type f | xargs cat
  - cd ~/.config/wahoo; tree -h; find . -type f | xargs cat
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/281fd475b5a3cedd8f5d
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: false     # default: false
